server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/acadlink}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver
  flyway:
   enabled: true
   # locations: classpath:db/migration # If necessary.
   baseline-on-migrate: true
   baseline-version: 1

  jpa:
    hibernate:
      ddl-auto: validate  # use "validate" in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#   mail:
#     host: smtp.gmail.com
#     port: 587
#     username: acadlink07@gmail.com
#     password: vvbh dugi urcw ovqu
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true

jwt:
  secret: acadlinkSecretKey
  expiration: 86400000  # 1 day

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
